"""remove start_date and end_date from player_team_season

Revision ID: 1f7d5f565fae
Revises: 4b2cff9b9de2
Create Date: 2026-03-22 21:53:15.497536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f7d5f565fae'
down_revision = '4b2cff9b9de2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_team_season', schema=None) as batch_op:
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_team_season', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.DATE(), nullable=True))

    # ### end Alembic commands ###
