"""add nhl models

Revision ID: 4b2cff9b9de2
Revises: 
Create Date: 2026-03-19 14:18:10.294144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b2cff9b9de2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('nationality', sa.String(length=50), nullable=False),
    sa.Column('shoot_catches', sa.String(length=20), nullable=False),
    sa.Column('primary_position', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('season',
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('season_id')
    )
    op.create_table('team',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('abbreviation', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('team_id'),
    sa.UniqueConstraint('abbreviation')
    )
    op.create_table('game',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('game_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=False),
    sa.Column('away_score', sa.Integer(), nullable=False),
    sa.Column('overtime_flag', sa.Boolean(), nullable=False),
    sa.Column('shootout_flag', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['team.team_id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['team.team_id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['season.season_id'], ),
    sa.PrimaryKeyConstraint('game_id')
    )
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.create_index('idx_game_season_date', ['season_id', 'game_date'], unique=False)

    op.create_table('player_team_season',
    sa.Column('player_team_season_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('jersey_number', sa.String(length=10), nullable=True),
    sa.Column('listed_position', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['season.season_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], ),
    sa.PrimaryKeyConstraint('player_team_season_id'),
    sa.UniqueConstraint('player_id', 'team_id', 'season_id', name='uq_player_team_season')
    )
    with op.batch_alter_table('player_team_season', schema=None) as batch_op:
        batch_op.create_index('idx_pts_player_season', ['player_id', 'season_id'], unique=False)

    op.create_table('player_game_stats',
    sa.Column('player_game_stats_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('shots', sa.Integer(), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('pim', sa.Integer(), nullable=False),
    sa.Column('toi_seconds', sa.Integer(), nullable=False),
    sa.Column('plus_minus', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.game_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], ),
    sa.PrimaryKeyConstraint('player_game_stats_id'),
    sa.UniqueConstraint('game_id', 'player_id', name='uq_player_game')
    )
    with op.batch_alter_table('player_game_stats', schema=None) as batch_op:
        batch_op.create_index('idx_pgs_game_id', ['game_id'], unique=False)
        batch_op.create_index('idx_pgs_player_id', ['player_id'], unique=False)

    op.create_table('team_game_stats',
    sa.Column('team_game_stats_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('shots', sa.Integer(), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('pim', sa.Integer(), nullable=False),
    sa.Column('faceoff_win_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('powerplay_goals', sa.Integer(), nullable=False),
    sa.Column('powerplay_opportunities', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.game_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], ),
    sa.PrimaryKeyConstraint('team_game_stats_id'),
    sa.UniqueConstraint('team_id', 'game_id', name='uq_team_game')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_game_stats')
    with op.batch_alter_table('player_game_stats', schema=None) as batch_op:
        batch_op.drop_index('idx_pgs_player_id')
        batch_op.drop_index('idx_pgs_game_id')

    op.drop_table('player_game_stats')
    with op.batch_alter_table('player_team_season', schema=None) as batch_op:
        batch_op.drop_index('idx_pts_player_season')

    op.drop_table('player_team_season')
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_index('idx_game_season_date')

    op.drop_table('game')
    op.drop_table('team')
    op.drop_table('season')
    op.drop_table('player')
    # ### end Alembic commands ###
