"""add headshot_url to player

Revision ID: d160a3e72aec
Revises: 1f7d5f565fae
Create Date: 2026-03-23 20:18:32.161967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd160a3e72aec'
down_revision = '1f7d5f565fae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('headshot_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('headshot_url')

    # ### end Alembic commands ###
